tracks: load tracks from wikiloc url
wladich/nakarte pull request #763
Opened 2021-06-16 19:14 UTC by sikmir

Resolves #252
Test urls:
* https://www.wikiloc.com/hiking-trails/tropa-zaitsa-74572795 (with wayponts)
* https://www.wikiloc.com/kayaking-canoeing-trails/202106-petrovskiy-marathon-75037824 (no waypoints)
* https://ru.wikiloc.com/marshruty-baidarki/202106-petrovskiy-marathon-75037824 (ru)

2021-06-26 19:05 UTC, wladich commented
Я наконец починил все сломанные PR-ы  от dependabot, теперь можно отребейзить этот RP на мастер.
Я посмотрел - сходу не работает, пишет `ReferenceError: Buffer is not defined`

Ещё надо обернуть парсинг в try-catch, иначе если сервер вернёт что-то неожиданное, то диалог останется в состоянии "загрузка" без сообщений пользователю  (как сейчас и происходит, но не из-за ответа сервера, а из-за ReferenceError)

2021-06-26 19:18 UTC, sikmir commented
> Я посмотрел - сходу не работает, пишет `ReferenceError: Buffer is not defined`

Хм, через `yarn start` у меня все работает, а вот если собирать через `yarn run build`, то действительно ошибка.

2021-06-27 18:45 UTC, wladich requested changes

2021-06-27 18:45 UTC, wladich commented on src/lib/leaflet.control.track-list/lib/services/wikiloc.js
> +            return [{error: 'Wikiloc trail does not exist'}];
Для несуществующих ID сервер возвращает 404 и, поскольку в requestOptions не указано, что 404 это ожидаемый ответ, получаем ошибку NETWORK. В этом можно убедиться, введя в поле над треками "https://www.wikiloc.com/hiking-trails/tropa-zaitsa-745727951" -  получаем сообщение "Could not download file from url", а не то, что написано в этой строке.

Соответственно, в это место мы можем попасть только если трек существует, но формат данных изменился и регулярка не сработала, а этот случай называется UNSUPPORTED

2021-06-27 18:45 UTC, wladich commented on src/lib/leaflet.control.track-list/lib/services/wikiloc.js
> +                name: data.mapData[0].nom,
Если не окажется mapdata[0] или .nom, то случится исключение или будет пустое имя. Надо добавить дефолт типа 
```
mapdata?.[0]?.nom ?? `Wikiloc track ${trackId}` 
```

2021-06-27 18:45 UTC, wladich commented on src/lib/leaflet.control.track-list/lib/services/wikiloc.js
> +            return [{error: 'UNSUPPORTED'}];
Для UNSUPPORTED требуется имя в поле name для форматирования сообщения об ошибке. Пример - в любом другом модуле чтения треков из внешних сервисов.

2021-06-29 14:59 UTC, wladich commented
Спасибо за PR

Смержил через #773, я там добавил тесты.

2021-06-29 14:59 UTC, closed without merging

2021-06-29 15:12 UTC, wladich commented
Раскатил на прод.
[Новость](https://draft.blogger.com/blog/post/edit/7213441819382735536/7536448905334769913)